# -*- coding: utf-8 -*-
# Generates sources.py from scratch/research/*.json and reports the value changes
# still needed in the source data (by comparing proposed vs live).
#
# File-name convention selects the target:
#   spec-*.json  -> SPECIALS  (SPEC_SOURCES, keyed by int n)
#   make-*.json  -> MAKES     (MAKE_SOURCES, keyed by str id; diffs build.calc salt/cure)
#   anything else-> CUTS      (CUT_SOURCES, keyed by int n)
import json, glob, os, pprint
import data
from sausages_new import NEW_SAUSAGES

FIELDS = {
    'sv':        [('svt','svt'), ('svh','svh')],
    'smoke':     [('smt','smt'), ('smh','smh'), ('tgt','tgt'), ('wood','wood')],
    'smoke_only':[('sot','sot'), ('soh','soh')],
    'safe':      [('safe','safe')],
}

def cite(o):
    if not isinstance(o, dict): return None
    d = {k: o[k] for k in ('ref','url','note') if o.get(k) is not None}
    return d or None

cuts_by_n = {c['n']: c for c in data.CUTS}
spec_by_n = {s['n']: s for s in data.SPECIALS}
makes_map = dict(data.MAKES); makes_map.update(NEW_SAUSAGES)

CUT_SOURCES, SPEC_SOURCES, MAKE_SOURCES = {}, {}, {}
report = []

def add_entry(dest, key, entry):
    if key in dest:
        dest[key]['src'].update(entry.pop('src'))
        dest[key].update(entry)
    else:
        dest[key] = entry

for path in sorted(glob.glob('scratch/research/*.json')):
    base = os.path.basename(path)
    kind = 'spec' if base.startswith('spec-') else 'make' if base.startswith('make-') else 'cut'
    items = json.load(open(path, encoding='utf-8'))
    for it in items:
        src = {}
        for key in ('sv','smoke','safe','grill','cure','process'):
            c = cite(it.get(key))
            if c: src[key] = c
        src['verified'] = '2026-07-12'
        entry = {'src': src}
        if it.get('order_svsmoke'): entry['order_svsmoke'] = it['order_svsmoke']
        if it.get('order_smokesv'): entry['order_smokesv'] = it['order_smokesv']
        g = it.get('grill')
        if isinstance(g, dict):
            for k in ('grt','grh','grz','grillable'):
                if g.get(k) is not None: entry[k] = g[k]

        if kind == 'make':
            mid = it['id']
            cur = (makes_map.get(mid, {}).get('build') or {}).get('calc') or {}
            o = it.get('calc') or {}
            override, diffs = {}, []
            for fld in ('salt', 'cure'):
                if o.get(fld) is not None and str(cur.get(fld)) != str(o[fld]):
                    override[fld] = o[fld]
                    diffs.append(f"{fld}: {cur.get(fld)!r} -> {o[fld]!r}")
            if override: entry['calc'] = override          # only changed calc fields are overridden
            add_entry(MAKE_SOURCES, mid, entry)
            if diffs: report.append(('MAKE', mid, it.get('eng',''), diffs))
            continue

        n = it['n']
        dest = SPEC_SOURCES if kind == 'spec' else CUT_SOURCES
        cur = (spec_by_n if kind == 'spec' else cuts_by_n).get(n, {})
        add_entry(dest, n, entry)
        diffs = []
        for grp, fields in FIELDS.items():
            o = it.get(grp) or {}
            for pk, dk in fields:
                if o.get(pk) is not None and str(cur.get(dk)) != str(o[pk]):
                    diffs.append(f"{dk}: {cur.get(dk)!r} -> {o[pk]!r}")
        if diffs: report.append(('SPEC' if kind == 'spec' else 'CUT', n, it.get('eng',''), diffs))

with open('sources.py', 'w', encoding='utf-8') as f:
    f.write('# -*- coding: utf-8 -*-\n')
    f.write('# AUTO-GENERATED by gen_sources.py from scratch/research/*.json. Do not hand-edit.\n\n')
    f.write('CUT_SOURCES = ' + pprint.pformat(CUT_SOURCES, sort_dicts=False, width=118) + '\n\n')
    f.write('SPEC_SOURCES = ' + pprint.pformat(SPEC_SOURCES, sort_dicts=False, width=118) + '\n\n')
    f.write('MAKE_SOURCES = ' + pprint.pformat(MAKE_SOURCES, sort_dicts=False, width=118) + '\n')

print(f'CUT_SOURCES:{len(CUT_SOURCES)}  SPEC_SOURCES:{len(SPEC_SOURCES)}  MAKE_SOURCES:{len(MAKE_SOURCES)}')
# MAKE calc changes are applied at build time via the sources.py merge (build.calc),
# so they are DONE, not pending. CUT/SPEC diffs are pending data.py edits.
pending = [r for r in report if r[0] != 'MAKE']
applied = [r for r in report if r[0] == 'MAKE']
print('=== MAKE calc overrides (APPLIED via sources.py merge) ===')
for tag, key, eng, diffs in applied:
    print(f'{tag:<4} {str(key):<16} {eng:<26} ' + ' | '.join(diffs))
print(f'({len(applied)} make calc overrides applied)')
print('=== CUT/SPEC value changes (PENDING data.py edits) ===')
for tag, key, eng, diffs in pending:
    print(f'{tag:<4} {str(key):<16} {eng:<26} ' + ' | '.join(diffs))
print(f'({len(pending)} pending data.py edits)')
