#!/bin/sh
# scripts/graphify-doc-trigger.sh — incremental DOCUMENT graph refresh trigger.
#
# WHY THIS EXISTS: `graphify hook install` only wires a CODE-graph rebuild
# (`graphify.watch._rebuild_code`, "no LLM needed"). Document freshness still
# required a manual `graphify extract docs --mode deep`, which is LLM-backed
# and was being run as an infrequent, hours-long full sweep. Full derivation
# and the proof this is safe: docs/process/graph-freshness-automation.md.
#
# MECHANISM (proven empirically on a scratch corpus, not assumed):
#   - `graphify extract <dir> --mode deep` (no --force) is INCREMENTAL and
#     CONTENT-HASH keyed: graphify-out/manifest.json stores an md5 of each
#     file's raw bytes, and a file is only re-dispatched to the LLM when that
#     hash differs from the stored one. A `touch` with no content change is a
#     cache HIT, not a miss — the gate does not key on mtime.
#   - Re-running on a whole directory when only 1 of N files actually changed
#     re-dispatches only that 1 file (observed: "semantic cache: 1 hit / 1
#     miss") and the written graph.json MERGES the new node(s) with the
#     untouched ones from cache (observed: node from the unchanged file
#     survived the run) — not a destructive overwrite.
#   - If extraction produces zero nodes (e.g. no backend/key available),
#     graphify prints an error and writes NOTHING — graph.json is left as-is.
#     That is the fail-safe property this script relies on: it never needs to
#     pre-check "is a key configured", it just runs extract and treats a
#     non-zero exit as an already-safe no-op.
#   - So pointing this at the whole `docs/` tree after every commit is cheap
#     in the common case (a commit usually touches 1-3 doc files) even though
#     the historical "5 hit / 191 miss" number looked alarming — that number
#     was an accumulated backlog from infrequent manual runs, not evidence of
#     a broken gate (verified by recomputing md5 for every docs/**/*.md file
#     against the manifest: only the files that actually differed were
#     misses).
#
# WHY post-commit AND NOT: an OS-level FileSystemWatcher (editors autosave
# constantly; a naive watcher fires per keystroke-save with no natural
# debounce and would burn LLM calls on half-written files) · a pre-push hook
# (by push time a commit backlog has accumulated again, reintroducing the
# "big batch, long run" problem this design exists to avoid; the freshness
# gate at push is a backstop, not the trigger) · a periodic scheduled job
# (decoupled from actual changes: wastes cycles on quiet days, lags behind
# on busy ones). A git commit is already an atomic, content-addressed unit of
# change — the natural debounce boundary.
#
# FAILS SAFE: runs detached (commit returns immediately); a lockfile means a
# burst of rapid commits queues rather than races; a backend/key gap is
# logged, not fatal, and never blocks or fails the commit.
#
# WIRING: `.git/hooks/post-commit` is regenerated by `graphify hook install`
# and is NOT tracked in git — this script is called from a block appended
# AFTER that tool's `# graphify-hook-end` marker. If `graphify hook install`
# is ever re-run, verify the tail of `.git/hooks/post-commit` still contains
# the "graphify doc-trigger" call block below; re-append from this file's
# header comment if it was dropped.
#
#   sh scripts/graphify-doc-trigger.sh
# is also safe to run by hand at any time (e.g. to catch up a backlog).

[ "${GRAPHIFY_SKIP_DOC_HOOK:-0}" = "1" ] && exit 0

GIT_DIR=${GIT_DIR:-$(git rev-parse --git-dir 2>/dev/null)}
[ -d "$GIT_DIR/rebase-merge" ] && exit 0
[ -d "$GIT_DIR/rebase-apply" ] && exit 0
[ -f "$GIT_DIR/MERGE_HEAD" ] && exit 0
[ -f "$GIT_DIR/CHERRY_PICK_HEAD" ] && exit 0

CHANGED_DOCS=$(git diff --name-only HEAD~1 HEAD -- 'docs/*.md' 'docs/**/*.md' 2>/dev/null)
if [ -z "$CHANGED_DOCS" ]; then
    # Manual/backfill invocation (no HEAD~1 diff, e.g. run by hand): still
    # worth a run since the manifest gate makes it cheap when nothing changed.
    [ "${1:-}" != "--force-check" ] && exit 0
fi

mkdir -p graphify-out
LOG="${HOME}/.cache/graphify-doc-rebuild.log"
mkdir -p "$(dirname "$LOG")"
LOCK="graphify-out/.doc-extract.lock"

if [ -f "$LOCK" ]; then
    LOCK_PID=$(cat "$LOCK" 2>/dev/null)
    if [ -n "$LOCK_PID" ] && kill -0 "$LOCK_PID" 2>/dev/null; then
        echo "[graphify doc-trigger] $(date -Iseconds 2>/dev/null || date) already running (pid $LOCK_PID) - this commit's doc changes ride the file-content hash and will be caught by that run or the next trigger." >> "$LOG"
        exit 0
    fi
    rm -f "$LOCK"
fi

# Unset/override to pick a specific backend (auto-detects from whichever API
# key is present otherwise, per `graphify extract --help`).
BACKEND_ARGS="${GRAPHIFY_DOC_BACKEND_ARGS:-}"

(
    echo $$ > "$LOCK"
    echo "[graphify doc-trigger] $(date -Iseconds 2>/dev/null || date) start - changed: ${CHANGED_DOCS:-<manual run>}" >> "$LOG"
    # shellcheck disable=SC2086
    graphify extract docs --mode deep $BACKEND_ARGS >> "$LOG" 2>&1
    STATUS=$?
    if [ $STATUS -ne 0 ]; then
        echo "[graphify doc-trigger] extract exited $STATUS - commonly means no LLM backend/key is configured in this shell's environment. graph.json is untouched (graphify fails safe on this path); run manually once a backend is available. See docs/process/graph-freshness-automation.md." >> "$LOG"
    else
        echo "[graphify doc-trigger] $(date -Iseconds 2>/dev/null || date) done (exit 0)" >> "$LOG"
    fi
    rm -f "$LOCK"
) &
disown 2>/dev/null || true

echo "[graphify doc-trigger] doc change detected - incremental refresh launched in background (log: $LOG)"
exit 0
